<?php
/**
 * Author: feiber
 * Blog:
 * Email:
 * Created at: 2016-10-16 17:15
 */

namespace common\models;

use common\helpers\Util;
use Yii;

/**
 * This is the model class for table "{{%content}}".
 *
 * @property string  $id
 * @property string  $aid
 * @property string  $content
 * @property Article $a
 */
class ArticleContent extends \yii\db\ActiveRecord
{
    public $local_images = 0;
    public $auto_replace = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%article_content}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['aid'], 'required'],
            [['aid', 'auto_replace', 'local_images'], 'integer'],
            [['content'], 'string'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'      => Yii::t('app', 'ID'),
            'aid'     => Yii::t('app', 'Aid'),
            'content' => Yii::t('app', 'Content'),
        ];
    }

    public function beforeSave($insert)
    {
        $this->content = str_replace('src="' . Yii::$app->params['site']['url'], 'src="', $this->content);
        (empty($this->auto_replace)) && $this->content = Util::getInstance()->contentReplace($this->content);
        if (
            strpos($this->content, '45fan.com') !== false || $this->local_images == 1
        ) {
            preg_match_all('/<img.*src="(.*)"/isU', $this->content, $matches);
            if (isset($matches[1]) && !empty($matches[1])) {
                $uploadDir = 'article/' . date('Y-m') . '/';
                $matches[1] = array_unique($matches[1]);
                foreach ($matches[1] as $val) {
                    $imgSrcPath = Util::getInstance()->getImgWater($val, $uploadDir);
                    if (!empty($imgSrcPath)) {
                        $this->content = str_replace($val, $imgSrcPath, $this->content);
                    }
                }
            }
        }

        return true;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!$insert && strpos($changedAttributes['content'], 'src="/uploads')) {
            $pattern = '/<img.*src="(.*)"/isU';
            preg_match_all($pattern, $changedAttributes['content'], $oldMatches);
            $oldMatches[1] = array_unique($oldMatches[1]);
            preg_match_all($pattern, $this->content, $newMatches);
            $newMatches[1] = array_unique($newMatches[1]);
            $diffImgs = (array_diff($oldMatches[1], $newMatches[1]));
            if (!empty($diffImgs)) {
                foreach ($diffImgs as $diffImg) {
                    $file = Yii::getAlias('@frontend/web') . $diffImg;
                    (file_exists($file) && is_file($file)) && unlink($file);
                }
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $baseUrl = Yii::$app->params['site']['url'];
        $this->content = str_replace(Yii::$app->params['site']['sign'], $baseUrl, $this->content);
    }
}
