<?php
/**
 * Author: feiber
 * Blog:
 * Email:
 * Created at: 2017-03-15 21:16
 */

namespace common\models;

use Overtrue\Pinyin\Pinyin;
use Yii;
use yii\base\Exception;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use common\libs\FamilyTree;

/**
 * This is the model class for table "{{%category}}".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string  $name
 * @property string  $alias
 * @property string  $seo_title
 * @property string  $seo_keywords
 * @property string  $seo_description
 * @property integer $sort
 * @property string  $html_path
 * @property string  $template
 * @property string  $article_template
 * @property string  $remark
 * @property integer $created_at
 * @property integer $updated_at
 */
class Category extends \yii\db\ActiveRecord
{

    use FamilyTree;

    public $level;

    public $prefix_level_name;

    private $updateHtmlPath = false;

    private $oldHtmlPath = null;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%category}}';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sort', 'parent_id', 'created_at', 'updated_at'], 'integer'],
            [['sort'], 'compare', 'compareValue' => 0, 'operator' => '>='],
            [['parent_id'], 'default', 'value' => 0],
            [['remark', 'seo_description'], 'string', 'max' => 255],
            [['template', 'article_template', 'html_path'], 'string', 'max' => 200],
            [['name', 'alias'], 'string', 'max' => 100],
            [['seo_title',], 'string', 'max' => 150],
            [['seo_keywords'], 'string', 'max' => 50],
            [['alias'], 'match', 'pattern' => '/^[a-zA-Z0-9_]+$/', 'message' => Yii::t('app', 'Must begin with alphabet and can only includes alphabet,_,and number')],
            [['name'], 'required'],
            [['sort'], 'default', 'value' => 0],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'               => Yii::t('app', 'ID'),
            'parent_id'        => Yii::t('app', 'Parent Category Id'),
            'name'             => Yii::t('app', 'Name'),
            'alias'            => Yii::t('app', 'Alias'),
            'seo_title'        => 'SEO 标题',
            'seo_keywords'     => 'SEO 关键词',
            'seo_description'  => 'SEO 摘要',
            'sort'             => Yii::t('app', 'Sort'),
            'template'         => Yii::t('app', 'Category Template'),
            'article_template' => Yii::t('app', 'Article Template'),
            'remark'           => Yii::t('app', 'Remark'),
            'created_at'       => Yii::t('app', 'Created At'),
            'updated_at'       => Yii::t('app', 'Updated At'),
        ];
    }

    public function getItems()
    {
        return self::_getCategories();
    }

    /**
     * @return array|\yii\db\ActiveRecord[]
     */
    protected static function _getCategories()
    {
        return self::find()->orderBy(['sort' => SORT_ASC, 'parent_id' => SORT_ASC])->all();
    }

    public function beforeSave($insert)
    {
        empty($this->alias) && $this->alias = (new Pinyin())->permalink($this->name, '');
        $parents = $this->getAncestors($this->parent_id);
        $this->html_path = '';
        if (!empty($parents)) {
            $parents = array_reverse($parents);
            foreach ($parents as $parent) {
                $this->html_path .= '/' . (($parent['id'] == $this->id) ? $this->alias : $parent['alias']);
            }
        }
        $this->html_path .= '/' . $this->alias;

        if (!$insert && $this->attributes['alias'] !== $this->oldAttributes['alias']) {
            $this->updateHtmlPath = true;
            $this->oldHtmlPath = $this->oldAttributes['html_path'] . '/';
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function beforeDelete()
    {
        $subs = $this->getDescendants($this->id);
        if (!empty($subs)) {
            $this->addError('id', Yii::t('app', 'Allowed not to be deleted, sub level existed.'));

            return false;
        }
        if (Article::findOne(['cid' => $this->id]) != null) {
            $this->addError('id', Yii::t('app', 'Allowed not to be deleted, some article belongs to this category.'));

            return false;
        }
        //        FileHelper::unlink(Yii::getAlias('@frontend/web') . $this->html_path);

        return parent::beforeDelete();
    }

    /**
     * @inheritdoc
     */
    public function afterValidate()
    {
        if (!$this->getIsNewRecord()) {
            if ($this->id == $this->parent_id) {
                $this->addError('parent_id', Yii::t('app', 'Cannot be themselves sub'));

                return false;
            }
            $descendants = $this->getDescendants($this->id);
            $descendants = ArrayHelper::getColumn($descendants, 'id');
            if (in_array($this->parent_id, $descendants)) {
                $this->addError('parent_id', Yii::t('app', 'Cannot be themselves descendants sub'));

                return false;
            }
        }
        parent::afterValidate();
    }

    public function afterSave($insert, $changedAttributes)
    {
        $frontendWebPath = Yii::getAlias('@frontend/web');
        //        if ($this->updateHtmlPath === true && !empty($this->oldHtmlPath)) {
        //            $table = self::tableName();
        //            $replace = $this->html_path . '/';
        //            $sql = "update {$table} set html_path=replace(`html_path`,'{$this->oldHtmlPath}','{$replace}') where html_path like '{$this->oldHtmlPath}%'";
        //            if (empty(Yii::$app->db->createCommand($sql)->execute()) || rename($frontendWebPath . $this->oldHtmlPath, $frontendWebPath . $replace) !== true) {
        //                throw new Exception('save category html path error');
        //            }
        //        } else {
        //            $htmlPath = $frontendWebPath . $this->html_path;
        //            !file_exists($htmlPath) && FileHelper::createDirectory($htmlPath);
        //        }
        self::_generateUrlRules();
        parent::afterSave($insert, $changedAttributes);
    }

    private function _generateUrlRules()
    {
        $categories = self::_getCategories();
        $data = [];
        foreach ($categories as $v) {
            $parents = $this->getAncestors($v['id']);
            $url = '';
            if (!empty($parents)) {
                $parents = array_reverse($parents);
                foreach ($parents as $parent) {
                    $url .= '/' . $parent['alias'];
                }
            }
            $url .= '/<cat:' . $v['alias'] . '>';
            $data[$url] = 'article/index';
        }
        $path = Yii::getAlias('@frontend/runtime/cache/');
        if (!file_exists($path)) FileHelper::createDirectory($path);
        file_put_contents($path . 'category.txt', json_encode($data));
    }

    public function getUrlRules()
    {
        $file = Yii::getAlias('@frontend/runtime/cache/category.txt');
        if (!file_exists($file)) {
            $this->_generateUrlRules();
        }

        return json_decode(file_get_contents($file), true);
    }

    public function getParent()
    {
        return $this->hasOne(self::className(), ['id' => 'parent_id']);
    }

}
